/*Q1*/

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, EMPLOYEES.DEPARTMENT_ID, DEPARTMENTS.DEPARTMENT_NAME
FROM HR.EMPLOYEES, HR.DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;

/*Q2*/

SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, DEPARTMENTS.DEPARTMENT_NAME, LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE
FROM(
HR.EMPLOYEES
	INNER JOIN HR.DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
    INNER JOIN HR.LOCATIONS ON LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID
);
    
/*Q3*/

/*This is wrong answer*/
SELECT EMPLOYEES.FIRST_NAME, EMPLOYEES.LAST_NAME, EMPLOYEES.SALARY, JOB_GRADES.GRADE_LEVEL
FROM HR.EMPLOYEES, HR.JOB_GRADES
WHERE EMPLOYEES.SALARY > JOB_GRADES.LOWEST_SAL AND EMPLOYEES.SALARY < JOB_GRADES.HIGHEST_SAL;

/*This is the correct answer*/
SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY, J.GRADE_LEVEL
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.JOB_GRADES AS J
    ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL
);

/*Q4*/

SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.DEPARTMENTS AS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
)
WHERE E.DEPARTMENT_ID = 40 OR E.DEPARTMENT_ID = 80;

/*Q5*/

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.DEPARTMENTS AS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
    INNER JOIN HR.LOCATIONS AS L ON D.LOCATION_ID = L.LOCATION_ID
)
WHERE FIRST_NAME LIKE "%z%";

/*Q6*/

SELECT D.DEPARTMENT_NAME
FROM(
HR.EMPLOYEES AS E
	RIGHT JOIN HR.DEPARTMENTS AS D
    ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
);

/*Q7*/

SELECT FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES
WHERE SALARY < (
	SELECT SALARY
    FROM HR.EMPLOYEES
    WHERE EMPLOYEE_ID = 182
);

SELECT E.FIRST_NAME, E.LAST_NAME, E.SALARY
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.EMPLOYEES AS S
		ON E.SALARY<S.SALARY AND S.EMPLOYEE_ID = 182
);

/* Both answers are correct */

/*Q8*/

SELECT E.FIRST_NAME, M.FIRST_NAME
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.EMPLOYEES AS M
		ON E.MANAGER_ID = M.EMPLOYEE_ID
);

/*Q9*/

SELECT D.DEPARTMENT_NAME, L.CITY, L.STATE_PROVINCE
FROM(
HR.DEPARTMENTS AS D
	INNER JOIN HR.LOCATIONS AS L
		ON D.LOCATION_ID = L.LOCATION_ID
);

/*Q10*/

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM(
HR.EMPLOYEES AS E
	LEFT JOIN HR.DEPARTMENTS AS D
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
);

/*Q11*/

SELECT E.FIRST_NAME, M.FIRST_NAME
FROM(
HR.EMPLOYEES AS E
	LEFT JOIN HR.EMPLOYEES AS M
		ON E.MANAGER_ID = M.EMPLOYEE_ID
);

/*Q12*/

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.EMPLOYEES AS D
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
        AND D.LAST_NAME = 'Taylor'
);

SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_ID
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.EMPLOYEES AS D
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
)
WHERE D.LAST_NAME = 'Taylor';

/*Q13*/

SELECT J.JOB_TITLE, D.DEPARTMENT_NAME, CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) AS FULL_NAME, JH.START_DATE, JH.END_DATE 
FROM(
HR.JOB_HISTORY AS JH
	INNER JOIN HR.JOBS AS J
		ON J.JOB_ID = JH.JOB_ID
	INNER JOIN HR.DEPARTMENTS AS D
		ON JH.DEPARTMENT_ID = D.DEPARTMENT_ID
	INNER JOIN HR.EMPLOYEES AS E
		ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
)
WHERE JH.START_DATE >= '1993-01-01'
	AND JH.END_DATE <= '1997-08-31';
    
/*Q14*/

SELECT J.JOB_TITLE, CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) AS FULL_NAME, J.MAX_SALARY-E.SALARY
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.JOBS AS J
		ON J.JOB_ID = E.JOB_ID
);

/*Q15*/

SELECT D.DEPARTMENT_NAME, AVG(E.SALARY), COUNT(E.EMPLOYEE_ID)
FROM(
HR.DEPARTMENTS AS D
	INNER JOIN HR.EMPLOYEES AS E
		ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
)
WHERE E.COMMISSION_PCT>0
GROUP BY D.DEPARTMENT_ID;

/*Q16*/

SELECT CONCAT(E.FIRST_NAME,' ', E.LAST_NAME) AS FULL_NAME, J.JOB_TITLE, J.MAX_SALARY-E.SALARY
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.JOBS AS J
		ON J.JOB_ID = E.JOB_ID
)
WHERE E.DEPARTMENT_ID = 80;

/*Q17*/

SELECT C.COUNTRY_ID, L.CITY, D.DEPARTMENT_NAME
FROM(
HR.COUNTRIES AS C
	INNER JOIN HR.LOCATIONS AS L
		ON L.COUNTRY_ID = C.COUNTRY_ID
	INNER JOIN HR.DEPARTMENTS AS D
		ON D.LOCATION_ID = L.LOCATION_ID
);

/*Q18*/

SELECT D.DEPARTMENT_NAME, CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME)
FROM(
HR.DEPARTMENTS AS D
	INNER JOIN HR.EMPLOYEES AS E
		ON D.MANAGER_ID = E.EMPLOYEE_ID
);

/*Q19*/

SELECT J.JOB_TITLE, AVG(SALARY)
FROM(
HR.JOBS AS J
	INNER JOIN HR.EMPLOYEES AS E
		ON E.JOB_ID = J.JOB_ID
)
GROUP BY J.JOB_TITLE;

/*Q20*/

SELECT J.JOB_ID, J.JOB_TITLE
FROM(
HR.JOBS AS J
	INNER JOIN HR.EMPLOYEES AS E
		ON E.JOB_ID = J.JOB_ID
        AND E.SALARY>=12000
);

/*Q21*/

SELECT C.COUNTRY_NAME, L.CITY, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM(
HR.COUNTRIES AS C
	INNER JOIN HR.LOCATIONS AS L
		ON L.COUNTRY_ID = C.COUNTRY_ID
	INNER JOIN HR.DEPARTMENTS AS D
		ON D.LOCATION_ID = L.LOCATION_ID
	INNER JOIN HR.EMPLOYEES AS E
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
)
GROUP BY D.DEPARTMENT_ID
HAVING COUNT(E.EMPLOYEE_ID) >2;

/*Q22*/

SELECT D.DEPARTMENT_NAME, CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME, L.CITY
FROM(
HR.DEPARTMENTS AS D
	INNER JOIN HR.EMPLOYEES AS E
		ON D.MANAGER_ID = E.EMPLOYEE_ID
	INNER JOIN HR.LOCATIONS AS L
		ON L.LOCATION_ID = D.LOCATION_ID
);

/*Q23*/

SELECT E.EMPLOYEE_ID, J.JOB_TITLE, TIMESTAMPDIFF(DAY, E.HIRE_DATE, SYSDATE())
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.JOBS AS J
		ON J.JOB_ID = E.JOB_ID
)
WHERE E.DEPARTMENT_ID = 80;

/*Q24*/

SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME, E.SALARY, E.EMPLOYEE_ID
FROM(
HR.EMPLOYEES AS E
	INNER JOIN HR.DEPARTMENTS AS D
		ON D.DEPARTMENT_ID = E.DEPARTMENT_ID
	INNER JOIN HR.LOCATIONS AS L
		ON D.LOCATION_ID = L.LOCATION_ID
)
WHERE L.CITY = 'London';

/*Q25*/

SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME, J.JOB_TITLE, JH.*
FROM(
HR.EMPLOYEES AS E
	INNER JOIN (
		SELECT MAX(START_DATE), MAX(END_DATE), EMPLOYEE_ID
        FROM HR.JOB_HISTORY
        GROUP BY EMPLOYEE_ID) AS JH
			ON E.EMPLOYEE_ID = JH.EMPLOYEE_ID
	INNER JOIN HR.JOBS AS J
		ON E.JOB_ID = J.JOB_ID
)
WHERE E.COMMISSION_PCT = 0;

SELECT CONCAT(e.first_name, ' ', e.last_name) AS Employee_name,
       j.job_title,
       h.*
FROM HR.employees e
JOIN
  (SELECT MAX(start_date),
          MAX(end_date),
          employee_id
   FROM HR.job_history
   GROUP BY employee_id) h ON e.employee_id=h.employee_id
JOIN HR.jobs j ON j.job_id=e.job_id
WHERE e.commission_pct = 0;

/*Q26*/

SELECT D.DEPARTMENT_NAME, COUNT(E.EMPLOYEE_ID) AS COUNT_OF_EMPLOYEES
FROM(
HR.DEPARTMENTS AS D
	INNER JOIN HR.EMPLOYEES AS E
		ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
)
GROUP BY D.DEPARTMENT_ID;

/*Q27*/

SELECT CONCAT(E.FIRST_NAME, ' ', E.LAST_NAME) AS FULL_NAME, E.EMPLOYEE_ID, C.COUNTRY_NAME
FROM(
HR.EMPLOYEES AS E
	JOIN HR.DEPARTMENTS AS D
		ON D.DEPARTMENT_ID = E.EMPLOYEE_ID
	JOIN HR.LOCATIONS AS L
		ON L.LOCATION_ID = D.LOCATION_ID
	JOIN HR.COUNTRIES AS C
		ON L.COUNTRY_ID = C.COUNTRY_ID
);